In [46]:
import numpy as np
#from numpy import matrix

def printMatrix(matrix):
    rows,col,bir = matrix.shape
    print("printMatrix - Row: ", str(rows), "Column: ", str(col))
    lines = []
    for row in matrix:
        lines.append(' '.join(str(x) for x in row))
    print('\n'.join(lines))

A = np.matrix([[1,2],[3,4],[5,6]])

#y_matrix = []
n_signs = 10
#y_matrix = np.empty([0, n_signs])
y_matrix = []
for sign_count in range(0,n_signs):
        y_sign = np.zeros((1,n_signs), dtype=np.int)
        y_sign[0][sign_count] = 1
        #printMatrix(y_sign)
        y_matrix.append(y_sign)
        #y_matrix = np.concatenate((y_matrix, y_sign), axis=0)
y_matrix = np.array(y_matrix)
print("Shape: ", str(y_matrix.shape))
printMatrix(y_matrix)

Shape:  (10, 1, 10)
printMatrix - Row:  10 Column:  1
[1 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 1]


In [12]:
import os
import cv2
import numpy as np
##ha necessidade de ter a 2DArray ao contrario da 3D que está sendo carregada.
## 
generated_filepath = os.getcwd() + '\\Generated\\'
sign_count = 0
inputdir =  generated_filepath + str(sign_count) + '\\'
print("Filepath: ", inputdir)
x_matrix = []
for image in os.listdir(inputdir):
#identar
    #listDir = os.listdir(inputdir) #testando
    #image = listDir[1] #testando
    imageFilepath = inputdir + image
    img_matrix = cv2.imread(imageFilepath,0)
    img_array = np.ravel(img_matrix)
    x_matrix.append(img_array)
#endidentar
print(type(img_matrix))
x_matrix = np.array(x_matrix)
print(x_matrix.shape)
#printMatrix(img_matrix)

Filepath:  C:\Users\frede\OneDrive\Documentos\trafficSignRecognition\Jupyter\Generated\0\
<class 'numpy.ndarray'>
(500, 3136)


In [7]:
import os
generated_filepath = os.getcwd() + '\\Generated\\'
inputdir =  generated_filepath + str(0) + '\\'
listDir = os.listdir(inputdir);
print(listDir[1])



0_1.png
